spring:
  data:
    mongodb:
      host: 192.168.51.3
      port: 27017
      database: test


server:
  port: 8000

# logging:
#   config: classpath:logback-local.xml
#   config: classpath:logback-${spring.profiles.active}.xml